version: '3.8'

services:
  app:
    container_name: tasks-ai-dev
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./logs:/var/log/app
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-technical_test}
      - POSTGRES_SERVER=db
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - tasks-ai

  db:
    image: postgres:15-alpine
    container_name: tasks-ai-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-technical_test}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - tasks-ai
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-technical_test}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_dev:

networks:
  tasks-ai:
    driver: bridge
